---
title: "Breast Cancer Wisconsin"
format: html
echo: false
warning: false
message: false
---


```{r setup}
library(tidyverse)
library(ggtext)

theme_set(
    theme_minimal() +
    theme(
    axis.line.x.bottom = element_line(color = '#474747', linewidth = .3),
    axis.ticks.x= element_line(color = '#474747', linewidth = .3),
    axis.line.y.left = element_line(color = '#474747', linewidth = .3),
    axis.ticks.y= element_line(color = '#474747', linewidth = .3),
    panel.grid = element_line(linewidth = .3, color = 'grey80'),
    panel.grid.minor = element_blank(),
    axis.ticks.length = unit(-0.15, "cm"),
    plot.background = element_rect(fill = '#F0F0F0'),
    plot.title.position = "plot",
    plot.title = element_markdown(family = "Ubuntu", size = 14),
    plot.subtitle = element_markdown(margin = margin(0,0,20,0)),
    axis.title.x = element_markdown(family = "Ubuntu", hjust = .5, size = 9),
    axis.title.y = element_markdown(family = "Ubuntu", hjust = .5, size = 8),
    axis.text = element_markdown(family = "Chakra Petch", hjust = .5, size = 8, color = "#474747"),
    legend.position = "top",
    text = element_text(family = "Ubuntu"),
    plot.margin = margin(25, 25, 25, 25))
)
```

```{r load_data}
library(mlbench)
data(BreastCancer)
bc_data <- as_tibble(BreastCancer)
```

## Data overview
```{r skimr}

bc_data <- 
    bc_data |>
    janitor::clean_names() |>
    filter(!is.na(bare_nuclei))

bc_data |>
    skimr::skim()
```

Except the `id` column, all columns are factors are ranging from 1 (closest to benign) to 10 (most abnormal).

Only `16` samples have missing data from `bare_nuclei`. Removed.

Some class imbalance (444 `ben`, 234 `mal`).

## Data Exploration
```{r malignancy_degree}
# Collor pallet
colors <- c(
  "#2C003E",
  "#2D5F8C",
  "#BDC2C4",
  "#D98A59",
  "#781B1F",
  "#40001C" 
)
temp_palette <- colorRampPalette(colors)

prettify_varname <- function(varnames) {
  replacements <- c(
    "normal_nucleoli" = "Normal Nucleoli",
    "mitoses" = "Mitoses",
    "marg_adhesion" = "Marginal Adhesion",
    "epith_c_size" = "Epithelial Cell Size",
    "cl_thickness" = "Clump Thickness",
    "cell_size" = "Cell Size",
    "cell_shape" = "Cell Shape",
    "bl_cromatin" = "Bland Chromatin",
    "bare_nuclei" = "Bare Nuclei"
  )
  
  return(replacements[varnames])
}

# Plot

bc_data |>
    mutate(class = as.character(class)) |>
    mutate(across(where(~ is.factor(.) || is.ordered(.)), ~ as.numeric(as.character(.)))) |>
    pivot_longer(cols = -c('id','class'), names_to = 'variable', values_to = 'malig_degree') |>
    count(class, variable, malig_degree) |>
    group_by(class, variable) |>
    mutate(per = n / sum(n)) |>
    ungroup() |>
    ggplot(aes(x = per, y = variable)) + 
    geom_col(
        data = . %>% filter(class == 'benign'), 
        aes(fill = malig_degree), width = 0.3, just = 1) +
    geom_col(
        data = . %>% filter(class == 'malignant'), 
        aes(fill = malig_degree), width = 0.3, just = 0) +
    scale_fill_gradientn(colors = temp_palette(100)) +
    labs(
        x = 'Samples (%)', 
        y = NULL, 
        fill = "Malig. Degree", 
        title = '**Malignancy Degree**', 
        subtitle = 'Top row are cancer samples, bottom are benign. More red, more malignant.') +
    scale_x_continuous(label = scales::percent, expand = c(0,0,0,0)) +
    scale_y_discrete(expand = c(0.1,0,0,0), label = prettify_varname) +
    theme(
        axis.line.y.left = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank()) +
    guides(fill = 'none')

```

###  Doing some fun stuff
```{r radarplot}
bc_data |>
    mutate(class = as.character(class)) |>
    mutate(across(where(~ is.factor(.) || is.ordered(.)), ~ as.numeric(as.character(.)))) |>
    pivot_longer(cols = -c('id','class'), names_to = 'variable', values_to = 'malig_degree') |>
    count(class, variable, malig_degree) |>
    group_by(class, variable) |>
    mutate(per = n / sum(n)) |>
    ungroup() |>
    ggplot(aes(x = variable, y = per)) + 
    geom_col(
        aes(fill = malig_degree), width = 1.1) +
    scale_fill_gradientn(colors = temp_palette(100)) +
    scale_y_continuous(label = scales::percent, expand = c(0,0,0,0)) +
    scale_x_discrete(expand = c(0,0,0,0), label = prettify_varname) +
    theme_void() +
    facet_wrap(~class) +
    guides(fill = 'none') +
    coord_polar()

```

As expected, there is a huge difference between the two. Can we see on PCA? (PCA requires normal data


```{r pca}
my_color_manual <- c(
    "benign" = "#152424",
    "malignant" = "#B54534")

pca_results <- 
    bc_data |>
    mutate(class = as.character(class)) |>
    mutate(across(where(~ is.factor(.) || is.ordered(.)), ~ as.numeric(as.character(.)))) |>
    select(-id,-class) |> as.matrix() |>
    prcomp(center = TRUE, scale. = TRUE)


bc_data |> bind_cols(pca_results$x) |>
    ggplot(aes(x = PC1, y = PC2)) +
    geom_point(aes(color = class)) +
    scale_color_manual(values = my_color_manual, label = stringr::str_to_sentence) +
    coord_cartesian(ylim = c(-2.5,5), xlim = c(-8,4), expand = FALSE) +
    labs(
        x = str_c('PC1 (',scales::percent(summary(pca_results)$importance[2,1]),')'),
        y = str_c('PC2 (',scales::percent(summary(pca_results)$importance[2,2]),')'),
        color = NULL,
        title = '**Principal Component Analysis**')
```